name: Validate JSON

on:
  push:
    branches: [main]
    paths:
      - '**/*.json'
  pull_request:
    branches: [main]
    paths:
      - '**/*.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Checkout JSON validator
        uses: actions/checkout@v4
        with:
          repository: ThatOneFrench/Json-Validator
          path: Json-Validator
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Run JSON validator
        run: node json-validator.js
